name: Actions

on:
  pull_request:
    branches:
      - master

jobs:
  compile:
    name: Ensure Compiled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Ensure files are compiled
        run: |
          for DIR in */; do
            ( cd $DIR && npm i && npx @zeit/ncc build index.js )
          done

          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            echo 1
          fi
